Apiv3 3 most recent changes
Infomaniak/android-kDrive pull request #1067
Opened 2023-10-20 08:21 UTC by sirambd

2023-10-30 15:21 UTC, FabianDevel requested changes

2023-10-30 15:21 UTC, FabianDevel commented on app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
> +            customRealm = realm
```suggestion
            parentId = Utils.ROOT_ID,
            loadNextPage = false,
            ignoreCache = true,
            userDrive = userDrive,
            customRealm = realm,
```

2023-10-30 15:21 UTC, FabianDevel commented on app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
> +            customRealm = realm
```suggestion
            parentId = Utils.ROOT_ID,
            loadNextPage = false,
            ignoreCache = false,
            userDrive = userDrive,
            customRealm = realm,
```

2023-10-30 15:21 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesViewModel.kt
> +                    isFirstPage = isFirstPage
```suggestion
                    isFirstPage = isFirstPage,
```

2023-10-31 09:50 UTC, FabianDevel approved these changes

2023-11-09 08:47 UTC, tevincent approved these changes

2023-11-09 08:47 UTC, merged