Apiv3-4 clean code for trash
Infomaniak/android-kDrive pull request #1068
Opened 2023-10-20 08:24 UTC by sirambd

2023-10-31 09:23 UTC, FabianDevel requested changes

2023-10-31 09:23 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
> +            val data = apiResponse.data
This val is not useful

2023-10-31 09:29 UTC, FabianDevel approved these changes

2023-11-09 09:05 UTC, tevincent approved these changes

2023-11-09 09:05 UTC, merged