Apiv3-5 Migrate trash to apiV3
Infomaniak/android-kDrive pull request #1069
Opened 2023-10-20 08:26 UTC by sirambd

2023-10-31 10:34 UTC, FabianDevel approved these changes

2023-11-09 09:34 UTC, tevincent requested changes

2023-11-09 09:34 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
> +                        )
Même si on est sûr que apiResponse.data n'est pas null, pour moi on ne devrait pas avoir !!.

On pourrait faire:

```
apiResponse.data?.let {
    if (response.cursor == null) {
        ...
    } else {
        ...
    }
} ?: {
    driveTrashResults.postValue(null)
}
```

A force de s'autoriser les !!, il se peut qu'un jour, il y ait un vrai crash à cause de ça car on s'autorise de plus en plus à l'utiliser.

2023-11-09 16:57 UTC, KevinBoulongne approved these changes

2023-11-10 08:58 UTC, tevincent approved these changes

2023-11-10 09:39 UTC, merged