Apiv3-6 Gallery with cursor
Infomaniak/android-kDrive pull request #1072
Opened 2023-10-20 13:16 UTC by sirambd

2023-11-07 14:04 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
> +            else if (networkAvailable) galleryViewModel.loadMoreGallery(driveId, !networkAvailable)
```suggestion
            val isNetworkAvailable = mainViewModel.isInternetAvailable.value == true
            if (isRefresh) galleryViewModel.loadLastGallery(driveId, ignoreCloud = !isNetworkAvailable)
            else if (isNetworkAvailable) galleryViewModel.loadMoreGallery(driveId, ignoreCloud = false)

2023-11-07 14:56 UTC, FabianDevel requested changes

2023-11-07 14:56 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +        isFirstPage: Boolean = true,
The default value of isFirstPage is useless as it's 1 false and 1 true
Either remove this or the `isFirstPage = true`  in `loadLastGallery`

2023-11-07 14:56 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +    private fun fetchApiGallery(driveId: Int, isFirstPage: Boolean, cursor: String?): Pair<java.util.ArrayList<File>, Boolean>? {
Any reasons to use the java ArrayList instead of the kotlin one, or is it just a oversight ?

2023-11-07 14:56 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +        } else emitRealmGallery()
```suggestion
        return if (apiResponse.isSuccess()) {
            currentCursor = apiResponse.cursor
            emitApiGallery(apiResponse, isFirstPage)
        } else {
            emitRealmGallery()
        }
```

2023-11-09 17:00 UTC, KevinBoulongne requested changes

2023-11-09 17:00 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
> +            loadGallery(AccountUtils.currentDriveId, true)
```suggestion
            loadGallery(AccountUtils.currentDriveId, isRefresh = true)
```

2023-11-09 17:00 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
> +            loadGallery(AccountUtils.currentDriveId, true)
```suggestion
            loadGallery(AccountUtils.currentDriveId, isRefresh = true)
```

2023-11-10 07:41 UTC, FabianDevel approved these changes

2023-11-10 08:59 UTC, tevincent approved these changes

2023-11-16 08:38 UTC, KevinBoulongne approved these changes

2023-11-18 16:43 UTC, merged