Apiv3-8 File activities
Infomaniak/android-kDrive pull request #1110
Opened 2023-10-27 15:37 UTC by sirambd

2023-11-07 16:49 UTC, FabianDevel requested changes

2023-11-07 16:49 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
> +                    isFirstPage = !loadNextPage,
Won't this cause problems ? because you didn't inverted the check in if after that

2023-11-09 17:08 UTC, KevinBoulongne requested changes

2023-11-09 17:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/home/HomeViewModel.kt
> +
```suggestion

```

2023-11-09 17:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
> +        recursive(null)
```suggestion
        recursive(cursor = null)
```

2023-11-10 09:03 UTC, tevincent approved these changes

2023-11-18 16:44 UTC, merged