Apiv3-9 fix duplication data in gallery
Infomaniak/android-kDrive pull request #1112
Opened 2023-10-30 16:36 UTC by sirambd

This problem currently exists in production, but I prefer to fix it with v3 following all the changes.
Depends on #1110

2023-11-08 08:06 UTC, FabianDevel requested changes

2023-11-10 08:57 UTC, tevincent requested changes

2023-11-10 08:57 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +            galleryApiResult.value = lastGalleryFiles to galleryApiResult.value!!.second
Is it something we really want to crash here ? In my opinion, It would be better to display an error with an empty state instead of crashing.

2023-11-10 09:08 UTC, tevincent requested changes

2023-11-10 09:08 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +    val needToRestoreFiles get() = galleryApiResult.isInitialized
One thing I like to do is to always group public variables with each other and so on.

2023-11-10 09:08 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
> +    private var lastGalleryFiles = ArrayList<File>()
```suggestion
    private var lastGalleryFiles = arrayListOf<File>()
```

2023-11-22 15:49 UTC, FabianDevel approved these changes

2023-11-22 15:54 UTC, tevincent approved these changes

2023-11-22 16:07 UTC, merged