Improve the way we display PDF
Infomaniak/android-kDrive pull request #1128
Opened 2023-11-22 07:55 UTC by tevincent

2023-11-29 10:06 UTC, tevincent commented
Uploading new_handle_pdf.mp4…

2023-12-08 16:19 UTC, JorisBodin requested changes

2023-12-08 16:19 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/utils/PreviewPDFUtils.kt
> +    ): ApiResponse<java.io.File> {
Why don't you use `IOFile` there too?

2023-12-11 11:56 UTC, JorisBodin requested changes

2023-12-11 11:56 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
> +    private var pdfFile: java.io.File? = null
IOFile

2023-12-13 07:55 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/7af1105e-6a27-4059-9f56-d167729ec875

2023-12-13 15:30 UTC, JorisBodin approved these changes

2023-12-13 15:39 UTC, merged