Handle password protected PDF
Infomaniak/android-kDrive pull request #1131
Opened 2023-11-29 08:56 UTC by tevincent

2023-11-29 14:16 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/d8b829c8-b477-42d9-892e-887dd07eb324

2023-11-30 09:36 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/c04846e0-6c0f-4757-a488-92948204bf6e

2023-12-14 12:16 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/3c861f91-5dd1-4585-b73c-1d029c17342e

2023-12-14 16:16 UTC, FabianDevel requested changes

2023-12-14 16:16 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
> +            navigate(
We have a wrapping function called safeNavigate() that we always use instead of navigate

2023-12-14 16:16 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
> +            if (currentDestination?.id == R.id.pdfPasswordDialog) navigateUp()
I'm not really sure you should use navigateUp here, is there a special use ? 
We always use popBackStack(), what do you think about it ?

2023-12-14 16:16 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
> +        }
I think it should be better to have this in a ViewModel

2023-12-15 09:51 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PasswordDialogFragment.kt
> +            }
Since we're not using the return object from the `apply`, wouldn't be better to use `with` ?

2023-12-15 10:36 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PasswordDialogFragment.kt
> +            }
We use `apply` to modify the object and `with` just to use it.

2023-12-15 14:06 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/eadbfda6-abdd-457c-aa8e-af0704be6b5c

2023-12-18 13:09 UTC, FabianDevel requested changes
You should "reset" the error state when the dialog is dismissed to avoid keeping the error

2023-12-18 13:09 UTC, FabianDevel commented on app/src/main/res/layout/dialog_fragment_password.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Is it really useful to have a Constraint layout for only one view ? 
A simpler layout like a Linear could be enough I suppose

2023-12-18 13:09 UTC, FabianDevel commented on app/src/main/res/values-fr/strings.xml
> +    <string name="wrongPdfPassword">Mauvais mot de passe</string>
I don't really like this wording, I would find "Mot de passe incorrect" better

2023-12-20 16:09 UTC, FabianDevel approved these changes

2023-12-21 11:09 UTC, KevinBoulongne requested changes

2023-12-21 11:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/extensions/TextInputEditTextExtensions.kt
> +/*
The header goes above imports.

2023-12-21 11:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/extensions/TextInputEditTextExtensions.kt
> +
```suggestion
```

2023-12-21 11:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PasswordDialogFragment.kt
> +            //Here we set the listener to null because otherwise, the dialog is dismissed automatically when we press the button
```suggestion
            // Here we set the listener to null because otherwise, the dialog is dismissed automatically when we press the button
```

2023-12-27 14:39 UTC, tevincent commented
https://github.com/Infomaniak/android-kDrive/assets/149579879/7377857c-32fa-4050-a0a2-62a2e4fd88a4

2023-12-28 14:12 UTC, JorisBodin approved these changes

2023-12-28 14:12 UTC, merged