Clean UI settings
Infomaniak/android-kDrive pull request #1135
Opened 2023-12-12 12:54 UTC by FabianDevel

2023-12-15 13:43 UTC, LunarX requested changes

2023-12-15 13:43 UTC, LunarX commented on app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
You can copy the inner functions from mail what will prevent you from passing `sharedPreferences` as a receiver each time you call `sharedValue()`

2023-12-19 11:32 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
I'm not really a fan of these functions, it adds another layer of complexity where this is not really needed
Plus in mail there are a lot of settings, but there's less in kDrive

2023-12-19 11:51 UTC, LunarX commented on app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
Just to be sure, you'd just copy the ones we need in this file not all of the possible ones.

To me it doesn't add any layer of complexity. You just spare your time by not having to write `sharedPrefences.` every time because the function does it for you like a shortcut. You also don't need to care about that `sharedPrefences` instance anymore once it's setup.

You want a value stored in a shared pref? Give it a key and a default value and you're done. Nothing more, nothing less. Non need to bother with anything else

2023-12-19 11:57 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
To me it's just a sugar where I don't really see its usefulness as with autocompletion everything already writes itself, I find it not worth to create a wrapper to economize something like writing 2 characters and competing it,
then duplicating lines

2023-12-20 07:58 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
After team consultation : this is considered overkill

2023-12-21 11:03 UTC, KevinBoulongne requested changes

2023-12-21 11:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
> +    private val uiSettings by lazy { UiSettings(this) }
```suggestion
    private val uiSettings by lazy { UiSettings(context = this) }
```

2023-12-21 12:21 UTC, KevinBoulongne approved these changes

2023-12-21 15:24 UTC, JorisBodin approved these changes

2023-12-21 15:25 UTC, merged