Fix gallery crash
Infomaniak/android-kDrive pull request #1231
Opened 2024-02-29 09:46 UTC by LunarX

When navigating from the MenuGalleryFragment and back, clicking on the multiselect toolbar "move" or "trash" actions would crash the app during a `requireContext()` on the GalleryFragment instance because of poor GalleryFragment instance management

2024-02-29 14:58 UTC, tevincent requested changes

2024-02-29 14:58 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
> +        val galleryFragment = addGalleryFragment()
It's a bit weird to have a `addGaleryFragment` method which is doing 2 things, replacing the fragment AND returning the fragment itself.

2024-03-01 10:06 UTC, tevincent requested changes

2024-03-01 10:06 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
> +        val galleryFragment = addGalleryFragment()
Something like this?

```kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        ViewCompat.requestApplyInsets(binding.galleryListCoordinator)
        initFragment()
    }

    private fun initFragment() {
        getGalleryFragment()?.let { galleryFragment ->
            setUi(galleryFragment)
        } ?: run {
            childFragmentManager.beginTransaction()
                .replace(R.id.galleryFragmentView, GalleryFragment(), GalleryFragment.TAG)
                .commit()
        }
    }

    private fun getGalleryFragment() = (childFragmentManager.findFragmentByTag(GalleryFragment.TAG) as? GalleryFragment)
```

2024-03-01 10:28 UTC, tevincent requested changes

2024-03-01 10:28 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
> +        val galleryFragment = addGalleryFragment()
Maybe something like this?

```kotlin
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        ViewCompat.requestApplyInsets(binding.galleryListCoordinator)
        initFragment()
    }

    private fun initFragment() {
        val galleryFragment = getGalleryFragment() ?: GalleryFragment().also { displayDefaultFragment(it) }
        setUi(galleryFragment)
    }

    private fun displayDefaultFragment(defaultGalleryFragment: GalleryFragment) {
        childFragmentManager.beginTransaction()
            .replace(R.id.galleryFragmentView, defaultGalleryFragment, GalleryFragment.TAG)
            .commit()
    }
```

2024-03-06 06:35 UTC, KevinBoulongne approved these changes

2024-03-06 06:35 UTC, merged