In-App review in kDrive
Infomaniak/android-kDrive pull request #1242
Opened 2024-03-05 16:14 UTC by tevincent

2024-03-13 13:59 UTC, FabianDevel requested changes

2024-03-13 13:59 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +        InAppReviewManager(
put arguments name

2024-03-13 13:59 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +
```suggestion
```

2024-03-13 13:59 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +
```suggestion
```

2024-03-18 06:03 UTC, KevinBoulongne requested changes

2024-03-18 06:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +            feedbackUrlResId = R.string.urlUserReportAndroid
```suggestion
            feedbackUrlResId = R.string.urlUserReportAndroid,
```

2024-03-18 06:03 UTC, KevinBoulongne approved these changes

2024-03-18 07:13 UTC, FabianDevel approved these changes

2024-03-18 07:13 UTC, merged