Tidy offline ui to make it a bit easier to understand
Infomaniak/android-kDrive pull request #1244
Opened 2024-03-06 12:47 UTC by LunarX

2024-03-07 08:10 UTC, tevincent requested changes

2024-03-07 08:10 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
> +        val isItemInteractable = !isPendingOffline || file.currentProgress == 100
`isOfflineInProgress`? Interactable is a bit weird.

2024-03-07 09:36 UTC, tevincent approved these changes

2024-03-18 06:22 UTC, KevinBoulongne requested changes

2024-03-18 06:22 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
> +            // We can have a currentProgress in [0,99] yet the file is not pending?
Do we want to do something about this ?

2024-03-20 06:27 UTC, KevinBoulongne approved these changes

2024-03-20 06:32 UTC, merged