Print pdf inside and outside kDrive
Infomaniak/android-kDrive pull request #1279
Opened 2024-04-16 12:46 UTC by tevincent

2024-05-21 12:30 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +        extras: Bundle?
```suggestion
        extras: Bundle?,
```

2024-05-21 12:30 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +        callback?.onLayoutFinished(printInfo, true)
Can you name this `true` parameter ?

2024-05-21 12:30 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +        callback: WriteResultCallback?
```suggestion
        callback: WriteResultCallback?,
```

2024-05-21 12:30 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +                page.canvas.drawBitmap(bitmap, matrix, null)
Can you name this `null` parameter ?

2024-05-21 12:30 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +        }
I think we need to use `try catch finally` here.

2024-05-21 12:49 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/BitmapPrintDocumentAdapter.kt
> +        }
Yes.

2024-05-21 12:55 UTC, KevinBoulongne requested changes

2024-05-21 12:55 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
>              }
Can't add suggestion.

Replace with
```kt
            setOnClickListener { if (previewPDFHandler.isPasswordProtected) showPasswordDialog() else openWithClicked() }
```

2024-05-21 12:55 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
>                                  totalPage = pageCount
```suggestion
                                totalPage = pageCount,
```

2024-05-22 07:01 UTC, KevinBoulongne requested changes

2024-05-22 07:24 UTC, KevinBoulongne approved these changes

2024-05-22 07:25 UTC, merged