Remove important data from sentry
Infomaniak/android-kDrive pull request #1281
Opened 2024-04-18 09:14 UTC by FabianDevel

2024-04-18 09:54 UTC, KevinBoulongne requested changes

2024-04-18 09:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +                    SentryLog.i("kDrive", "Upload > File chunks number :$chunkNumber has permission")
```suggestion
                    SentryLog.i("kDrive", "Upload > File chunks number: $chunkNumber has permission")
```

2024-04-18 09:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +                    SentryLog.d("kDrive", "Upload > Start upload file to $url data size:${data.size}")
```suggestion
                    SentryLog.d("kDrive", "Upload > Start upload file to $url (data size:${data.size})")
```

2024-04-18 09:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> -            }
Why remove this whole Sentry ?

2024-04-18 09:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
> +                        scope.setExtra("Api responseAt", apiResponse.responseAt.toString())
```suggestion
                        scope.setExtra("API responseAt", apiResponse.responseAt.toString())
```

2024-04-18 09:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
> +                    scope.setExtra("Api responseAt", apiResponse.responseAt.toString())
```suggestion
                    scope.setExtra("API responseAt", apiResponse.responseAt.toString())
```

2024-04-19 09:47 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> -            }
Because it never triggered

2024-04-19 11:45 UTC, KevinBoulongne requested changes

2024-04-19 11:51 UTC, KevinBoulongne approved these changes

2024-04-19 11:54 UTC, merged