Fix tab inserting the toString of objects instead of autocompletion when sharing folder
Infomaniak/android-kDrive pull request #1316
Opened 2024-05-27 13:20 UTC by TommyDL-Infomaniak

The problem is mostly solved, pressing tab will not insert the object toString anymore, but it will insert the current text, thus not changing anything. 
A consequence of this is that the UI is refreshed and the list of users that was displayed gets closed.

This is the best solution found that does not require a refactor of the MaterialAutoCompleteTextView.

2024-05-28 09:10 UTC, KevinBoulongne requested changes

2024-05-28 09:16 UTC, KevinBoulongne requested changes

2024-05-28 09:16 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
>          notShareableEmails = notShareableEmails
```suggestion
        notShareableEmails = notShareableEmails,
```

2024-05-28 09:33 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +        getCurrentText = { return@AvailableShareableItemsAdapter text.toString() },
You can even remove do this to simplify : 
```suggestion
        getCurrentText = { text },
```

2024-05-28 09:47 UTC, FabianDevel requested changes
This creates a bug when you select a user then press enter

2024-05-28 11:02 UTC, LunarX requested changes

2024-05-28 11:02 UTC, LunarX commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +        notShareableEmails = notShareableEmails,
You could reorder these lines to keep the same ordering as inside the function declaration to make things easier to follow

2024-05-28 11:35 UTC, TommyDL-Infomaniak commented
> This creates a bug when you select a user then press enter

This has the same behavior as using tab.

2024-05-29 05:03 UTC, KevinBoulongne approved these changes

2024-05-30 10:39 UTC, LunarX approved these changes

2024-05-30 10:45 UTC, merged