Remove the gap between the bottom sheet and the bottom of the screen
Infomaniak/android-kDrive pull request #1330
Opened 2024-06-07 12:53 UTC by NicolasBourdin88

The gap is the result of set 'isFitContent' to false on the bottom sheet behavior but unfortunately it's either the gap or the half state on the bottom sheet.

The only solution that i founded is to fill the gap with 'match_parent' so we have half_state and no gap.

2024-06-07 14:27 UTC, tevincent commented
I want to test something. I'll let you know if I find something.

2024-06-10 13:58 UTC, tevincent commented
What we had before:

https://github.com/Infomaniak/android-kDrive/assets/149579879/b691d652-f81a-44de-8d33-f1a7fba049ff

The quickfix:

https://github.com/Infomaniak/android-kDrive/assets/149579879/95fc8ac8-912d-4c47-8a0c-cf692b523b64

With a custom class to handle the BottomSheet bahavior:
https://github.com/Infomaniak/android-kDrive/assets/149579879/9957da8b-e816-418e-bc31-4390694c4a71

2024-06-11 09:26 UTC, LunarX requested changes
This removes the native interaction behaviors that the bottom sheet naturally has makes it harder to use and less intuitive unfortunately

2024-06-12 12:39 UTC, KevinBoulongne commented
> This removes the native interaction behaviors that the bottom sheet naturally has makes it harder to use and less intuitive unfortunately

What does it remove ? Your comment is very unclear.

2024-06-13 08:16 UTC, merged