Use network status flow to know when we have internet or not
Infomaniak/android-kDrive pull request #1360
Opened 2024-07-18 09:36 UTC by tevincent

depends on https://github.com/Infomaniak/android-core/pull/208

https://github.com/user-attachments/assets/0c0d365b-2b22-4dcf-b5d9-652c2ab3cc51

2024-07-18 11:15 UTC, KevinBoulongne requested changes

2024-07-18 11:15 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
> +    }
```suggestion
    fun observeNetworkStatus() = viewModelScope.launch(Dispatchers.IO) {
        getContext().networkStatusFlow().collect { isAvailable ->
            SentryLog.d("Internet availability", if (isAvailable) "Available" else "Unavailable")
            Sentry.addBreadcrumb(
                Breadcrumb().apply {
                    category = "Network"
                    message = "Internet access is available : $isAvailable"
                    level = if (isAvailable) SentryLevel.INFO else SentryLevel.WARNING
                },
            )
            isInternetAvailable.postValue(isAvailable)
            if (isAvailable) {
                AccountUtils.updateCurrentUserAndDrives(this@MainViewModel.getContext())
                restartUploadWorkerIfNeeded()
            }
        }
    }
```

2024-07-22 05:23 UTC, KevinBoulongne approved these changes

2024-08-09 14:28 UTC, sirambd requested changes
At the moment, `mainViewModel.isNetworkAvailable.value` doesn't seem to work very well

2024-08-12 12:01 UTC, KevinBoulongne requested changes
The previous solution was fine.

Now, we are doing :
``` kotlin
viewModelScope.launch {
    isNetworkAvailable.collect {
        …
    }
}
```
everywhere in the UI.

That's pretty ugly.
Why this solution ?

2024-08-13 06:27 UTC, KevinBoulongne approved these changes

2024-08-13 06:37 UTC, KevinBoulongne requested changes

2024-08-13 06:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
> +            mainViewModel.isNetworkAvailable.collect { isNetworkAvailable ->
Use `.value` instead of collect ?

2024-08-13 07:28 UTC, sirambd requested changes
Do a global refactor to remove all useless imports

2024-08-13 07:28 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
> +        lifecycleScope.launch {
use `viewLifeCycleOwner.lifecyleScope` instead

2024-08-13 07:28 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +        lifecycleScope.launch {
use `viewLifecycleOwner.lifecycleScope` instead

2024-08-13 07:28 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +        lifecycleScope.launch {
This `launch` is really useful ?

2024-08-13 07:28 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +import kotlinx.coroutines.flow.first
I can't see where it's used

2024-08-13 07:55 UTC, sirambd approved these changes

2024-08-13 08:08 UTC, KevinBoulongne approved these changes

2024-08-13 08:08 UTC, merged