Potential fix of bug allowing a scan to be saved in invalid location
Infomaniak/android-kDrive pull request #1365
Opened 2024-07-24 09:12 UTC by TommyDL-Infomaniak

2024-07-25 07:08 UTC, tevincent requested changes

2024-07-25 07:08 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
> +                saveExternalFilesViewModel.folderId.value != -1
Use `OTHER_ROOT_ID`

2024-07-30 05:11 UTC, KevinBoulongne approved these changes

2024-07-30 07:51 UTC, tevincent approved these changes

2024-07-30 07:51 UTC, merged