Can now upload empty files
Infomaniak/android-kDrive pull request #1368
Opened 2024-07-26 12:01 UTC by TommyDL-Infomaniak

2024-07-29 06:06 UTC, KevinBoulongne requested changes

2024-07-29 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            ApiController.ApiMethod.POST,
Import `ApiController.`.

2024-07-29 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            okHttpClient = runBlocking { AccountUtils.getHttpClient(uploadFile.userId, 120) }
Magic number ?

2024-07-29 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            } else it.manageUploadErrors()
Add curly braces around `if` and `else`.

2024-07-29 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +                "&conflict=" + UploadTask.Companion.ConflictOption.RENAME.toString()
Import `UploadTask.Companion.`.

2024-07-29 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            route += "&directory_path=$remoteSubFolder"
Use `it` instead of `remoteSubFolder`.

2024-07-30 05:16 UTC, KevinBoulongne requested changes

2024-07-30 05:16 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            okHttpClient = runBlocking { AccountUtils.getHttpClient(uploadFile.userId, timeout = 120) }
```suggestion
            okHttpClient = runBlocking { AccountUtils.getHttpClient(uploadFile.userId, timeout = 120) },
```

2024-07-30 05:16 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            POST,
Put back `ApiMethod.`.
We import everything except the last class name.

That's why I said to _"Import `ApiController.`"_.

2024-07-30 05:16 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +            conflict = if (replaceOnConflict()) VERSION else RENAME,
Put back `ConflictOption.`.
We import everything except the last class name.

That's why I said to _"Import `UploadTask.Companion.`"_.

2024-07-30 05:16 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +                "&conflict=" + RENAME.toString()
Add `ConflictOption.`.

2024-08-06 07:33 UTC, sirambd requested changes

2024-08-06 07:33 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +    private fun UploadFile.uploadEmptyFileUrl(): String {
Move to ApiRepository, and avoid duplication with cloudStorage

2024-08-06 07:33 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
> +        if (UploadFile.canUpload(uri, fileModifiedAt, realm) && fileSize >= 0) {
We avoid synchronizing empty files, but we don't know what impact this will have on certain smartphones.

2024-08-06 12:16 UTC, sirambd requested changes

2024-08-06 12:16 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
> +    fun UploadFile.uploadUrl(uploadHost: String, chunkNumber: Int, currentChunkSize: Int): String {
Passes the `driveId` and `uploadToken` as parameters instead of passing through a `UploadFile` extension.

2024-08-06 12:16 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +    private suspend fun launchTaskEmptyFile() = withContext(Dispatchers.IO) {
This Dispatchers is useless

2024-08-06 12:16 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
> +    fun UploadFile.uploadUrl(uploadHost: String, chunkNumber: Int, currentChunkSize: Int): String {
The `urls` are in `ApiRoutes`.

2024-08-06 12:16 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
> +    fun uploadEmptyFileUrl(
Move to `ApiRoutes`

2024-08-07 12:58 UTC, sirambd requested changes

2024-08-07 12:58 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +    }
It fits very well on a line

2024-08-07 13:03 UTC, FabianDevel requested changes

2024-08-07 13:03 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +        )
oneline this

2024-08-07 13:03 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
> +    private fun launchTaskEmptyFile() {
This function should be in api repository

2024-08-07 13:08 UTC, KevinBoulongne approved these changes
Ok for me when all other comments are handled.

2024-08-09 09:08 UTC, FabianDevel approved these changes

2024-08-16 07:54 UTC, tevincent requested changes

2024-08-16 07:54 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
> +    private fun uploadFile(driveId: Int) = "${driveURL(driveId)}/upload"
Maybe it would be better to specify here that you return a URL ? Like `uploadChunkUrl` ? I noticed that we have both naming convention.

2024-08-20 07:37 UTC, sirambd approved these changes

2024-08-20 07:38 UTC, tevincent approved these changes

2024-08-20 07:38 UTC, merged