Add info to sentry when user logout
Infomaniak/android-kDrive pull request #1377
Opened 2024-08-07 12:14 UTC by NicolasBourdin88

Add user ID of disconnected user and number of remaining user, if 0 no user connected.

2024-08-07 14:15 UTC, LunarX commented on app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
> +            val remainingUserCountText = remainingUserCount?.toString() ?: "Failed to access value"
Maybe "null" is enough to understand we couldn't access it

2024-08-08 04:09 UTC, KevinBoulongne requested changes

2024-08-08 04:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
> +            SentryLog.i("logOut", "User logged out, disconnected user id: ${user.id}")
```suggestion
            SentryLog.i("logOut", "User logged out, remaining user count: ${AccountUtils.getAllUsersCount().minus(1)}")
            SentryLog.i("logOut", "User logged out, disconnected user id: ${user.id}")
```

2024-08-12 12:33 UTC, JorisBodin approved these changes

2024-08-13 06:54 UTC, KevinBoulongne approved these changes

2024-08-13 09:32 UTC, merged