04 Rename `fileShared` files to `publicShare`files
Infomaniak/android-kDrive pull request #1393
Opened 2024-08-16 11:48 UTC by FabianDevel

Depends on #1392 

This PR only rename the feature to avoid confusion with existing `FileShare`classes that represent the in-app management of a ShareLink.

2024-08-26 07:12 UTC, tevincent requested changes

2024-08-26 07:12 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
> +                            publicShareUuid = fileSharedLinkUuid,
Do you also want to rename `fileSharedLinkUuid` ?

2024-08-26 07:12 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/utils/Utils.kt
> +                publicShareUuid = shareLinkUuid,
Also here ? `shareLinkUuid`

2024-08-27 09:34 UTC, tevincent approved these changes

2024-09-16 10:45 UTC, tevincent requested changes

2024-09-17 06:57 UTC, sirambd approved these changes

2024-09-17 07:53 UTC, tevincent approved these changes

2024-09-17 08:23 UTC, merged