12 Allow to open URL files in public share
Infomaniak/android-kDrive pull request #1423
Opened 2024-09-13 06:35 UTC by FabianDevel

Depends on #1420 

We can now open URL file by clicking on it in the list

2024-09-16 12:37 UTC, tevincent requested changes

2024-09-16 12:37 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
> +                withContext(Dispatchers.Main) {
```suggestion
                Dispatchers.Main {
```

2024-09-16 12:37 UTC, tevincent commented on app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
> +            onDownloadSuccess = {},
Do we want to have a default value for `onDownloadSuccess` in `executeDownloadAction` ?

2024-09-17 11:29 UTC, sirambd approved these changes

2024-09-18 11:33 UTC, tevincent approved these changes

2024-09-18 14:29 UTC, merged