Migrate from the old exoPlayer to the new Media3 and add the possibility to play media in the background #1367
Infomaniak/android-kDrive pull request #1470
Opened 2024-10-17 05:33 UTC by tevincent

2025-03-28 08:31 UTC, tevincent commented
If PIP is killed, we should stop the player.

2025-03-28 12:25 UTC, FabianDevel requested changes

2025-03-28 12:25 UTC, FabianDevel commented on app/build.gradle
> +    compileSdk 35
Doesn't this cause problems because of Edge to edge ? 
We should wait for Sirambd's migration end before bumping no ?

2025-03-28 12:27 UTC, FabianDevel requested changes
We need to put back the "duration" matomo

EDIT: Done.

2026-07-10 11:48 UTC, FabianDevel requested changes

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +    @OptIn(UnstableApi::class)
Is it necessary here ? 
It looks like only the `@optIn` over finishPipActivity is required and this is oxbow code

2026-07-10 11:48 UTC, FabianDevel commented on gradle/libs.versions.toml
> +exoplayer = "1.10.1"
Shouldn't we rename this "media3" or "exoplayerMedia3" ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
> +    var positionsForMedia: MutableMap<Int, Long> = mutableMapOf()
```suggestion
    val positionsForMedia: MutableMap<Int, Long> = mutableMapOf()
```

mediaPositionsMap ? 
mediaPositions ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
> +    private fun initViewPager() = with(binding) {
We could make without this withbinding (only two binding usage)

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
> +
Why not directly setting ` onBackClicked = findNavController()::popBackStack,` at call site ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +            requireActivity().shouldExcludeFromRecents(false)
```suggestion
            requireActivity().shouldExcludeFromRecents(exclude = false)
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +            exoPlayerUIToHide.forEach { uiID -> findViewById<View>(uiID).isVisible = false }
findViewById can return null so i'd think we better put safe operator on them 
```suggestion
            exoPlayerUIToHide.forEach { uiID -> findViewById<View>(uiID)?.isVisible = false }
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +            binding.playerView.findViewById<View>(R.id.exo_play_pause).setOnClickListener {
```suggestion
            binding.playerView.findViewById<View>(R.id.exo_play_pause)?.setOnClickListener {
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +                    putExtra(VideoActivity.EXTRA_IS_PUBLIC_SHARED, isPublicShared)
Cannot this extra directly be in VideoActivityArgs ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/VideoActivity.kt
> +                    "Source error" -> previewDescription.setText(R.string.previewVideoSourceError)
Maybe add a constant for the error

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/VideoActivity.kt
> +            }
```suggestion
            if (videoFormat.width > videoFormat.height) Rational(16, 9) else Rational(9, 16)
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/VideoActivity.kt
> +                        SentryLog.e(TAG, "Cannot load file")
Should we display an error to the user also ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +        }
What about using a let with a `?: run {` to avoid the '!!' ? 

```suggestion
        mediaController?.let(::callback) ?: initController()
      
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +        if (mediaSession == null) {
We should avoid the nullcheck and handle the error here

```suggestion
       val player = activePlayer ?: run {
           showError()
           return
       }

        if (mediaSession == null) {
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +                addAnalyticsListener(EventLogger())
```suggestion
            .build()
            .apply {
                addAnalyticsListener(EventLogger())
```

What about this ?

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +        return Runnable {
```suggestion
    private fun getRunnable(callback: (MediaController) -> Unit) = Runnable {
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +                    }
```suggestion
                runCatching { mediaControllerFuture?.get()!! }
                    .onSuccess { controller ->
                        mediaController = controller
                        callback(controller)
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +                callback(mediaController!!)
Maybe use a let here also to avoid this null check ? 

I'm not 100% sure on the readability level though

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +        isPublicShared -> unauthenticatedHttpClient
This doesn't work, in public share the VideaoActivity closes each time

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackUtils.kt
> +        return object : MediaSession.Callback {
```suggestion
    private fun getMediaSessionCallback() = object : MediaSession.Callback {
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackViewModel.kt
> +                        remoteFile
```suggestion
                         FileController.getRemoteFile(fileId, userDrive.driveId, okHttpClient)?.also { remoteFile ->
                            FileController.saveRemoteFileToDb(remoteFile, userDrive, okHttpClient)
                        }
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PlaybackViewModel.kt
> +            }
```suggestion
            }.getOrNull()
```

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +        },
I think extracting to 2 function `onPlayingChange`and `onPlayerError` will be  cleaner

2026-07-10 11:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/playback/PreviewPlaybackFragment.kt
> +        if (file.isVideo().not()) {
I'd personnally prefer this

```suggestion
        if (!file.isVideo()) {
```

2026-07-14 11:32 UTC, FabianDevel approved these changes

2026-07-14 11:33 UTC, merged