Allow keyboard navigation
Infomaniak/android-kDrive pull request #1480
Opened 2024-11-01 13:58 UTC by NicolasBourdin88

Remove all keyboard traps and ensure that all interactive elements are focusable.

2025-02-20 08:54 UTC, LunarX commented
While navigating with the keyboard in order to activate the photo sync I had to select a folder. After a creating a new empty folder, I could not validate my folder choice with the keyboard, it seems to be focusing the background somehow instead. Am I missing an input?

<img width="622" alt="image" src="https://github.com/user-attachments/assets/0b4941bd-0c25-446b-91a1-2eeeaab01dc9" />

2025-02-20 08:58 UTC, LunarX commented
Also when picking what folders of my phone to sync, my choice isn't taken into account when leaving the screen using the keyboard to click on the top left cross. I don't even get how this is possible

2025-02-20 10:04 UTC, LunarX commented
Also when previewing a file in the view pager, I can't seem to reach to top toolbar with the keyboard

2025-02-20 10:09 UTC, LunarX commented
When navigating inside folders and then navigating back up a level, the folder I just left is not selected anymore. Do you think it would be possible to select again the folder "we came from"?

2025-02-20 10:29 UTC, LunarX requested changes
I've left the most important behaviors I've seen

2025-02-21 13:16 UTC, NicolasBourdin88 commented
> When navigating inside folders and then navigating back up a level, the folder I just left is not selected anymore. Do you think it would be possible to select again the folder "we came from"?

Summary:
After looking into a solution, it seems challenging because the approach we're using in Infomaniak Mail doesn’t work with RecyclerView due to **ID** and **tag** recomposition.

2025-02-25 09:32 UTC, LunarX requested changes
Also the toolbar of the fragment_ment_gallery is not accessible

2025-02-25 09:32 UTC, LunarX commented on app/src/main/java/com/infomaniak/drive/views/PreviewHeaderView.kt
> +        binding.pageNumberChip.isFocusable = false
Add a comment so we understand why this is not done inside xml directly maybe

2025-02-25 09:32 UTC, LunarX commented on app/src/main/res/layout/fragment_file_list.xml
> +                android:touchscreenBlocksFocus="true">
touchscreenBlocksFocus is also needed for nested scroll views? Or maybe rather, it's needed on the collapsing toolbar layout?

2025-02-25 09:32 UTC, LunarX commented on app/src/main/res/layout/fragment_home.xml
> +                android:touchscreenBlocksFocus="false"
Same question, is it needed on the collapsing toolbar here? Because you usually don't specify it on these views. Where exactly should this android:touchscreenBlocksFocus be placed?

2025-02-25 09:32 UTC, LunarX commented on app/src/main/res/layout/fragment_preview_slider.xml
> +            android:touchscreenBlocksFocus="true"
Do you need all 3?

2025-02-26 15:18 UTC, LunarX approved these changes

2025-02-27 08:16 UTC, merged