fix file not found in realm in file actions
Infomaniak/android-kDrive pull request #179
Opened 2021-08-11 07:55 UTC by sirambd

It is a fix for this error : 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.infomaniak.drive, PID: 8088
    java.lang.NullPointerException
        at com.infomaniak.drive.ui.bottomSheetDialogs.FileInfoActionsBottomSheetDialog.onViewCreated(FileInfoActionsBottomSheetDialog.kt:70)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2985)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1331)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2772)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2708)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2986)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1331)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2772)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2715)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

2021-08-12 13:36 UTC, JorisBodin requested changes

2021-08-12 13:36 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
> +        currentFile = FileController.getFileById(file.id, navigationArgs.userDrive) ?: file
No need to use "getFileById" anymore

2021-08-13 15:19 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
> +        currentFile = FileController.getFileById(file.id, navigationArgs.userDrive) ?: file
> No need to use "getFileById" anymore

Done

2021-08-19 13:39 UTC, Kilian-Perisset approved these changes

2021-08-19 16:31 UTC, JorisBodin approved these changes

2021-08-19 16:31 UTC, merged