Content observe delay
Infomaniak/android-kDrive pull request #256
Opened 2021-09-15 14:25 UTC by sirambd

2021-09-15 14:45 UTC, Kilian-Perisset requested changes

2021-09-15 14:45 UTC, Kilian-Perisset commented on app/src/main/java/com/infomaniak/drive/data/sync/FileObserveServiceApi24.kt
> +            ).setTriggerContentMaxDelay(5000)
Set this value in a constant (MAGIC_VALUE)

2021-09-16 15:30 UTC, JorisBodin requested changes

2021-09-16 15:30 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/data/sync/FileObserveService.kt
> +                                delay(5000)
Add TRIGGER_CONTENT_DELAY

2021-09-16 15:38 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/sync/FileObserveService.kt
> +                                delay(5000)
It's done 😊

2021-09-16 15:39 UTC, JorisBodin approved these changes

2021-09-16 15:40 UTC, Kilian-Perisset approved these changes

2021-09-16 15:40 UTC, merged