Fix load images in recyclerView and replace coil if needed - temp sol…
Infomaniak/android-kDrive pull request #327
Opened 2021-11-05 14:07 UTC by sirambd

…ution

Signed-off-by: Abdourahamane BOINAIDI <abdourahamane.boinaidi@infomaniak.com>

2021-11-05 14:28 UTC, KevinBoulongne approved these changes

2021-11-08 14:54 UTC, JorisBodin requested changes

2021-11-08 14:54 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +//            setupFileProgress(file)
Why?

2021-11-08 14:54 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> -                    filePreview.scaleType = ImageView.ScaleType.CENTER_CROP
Why?

2021-11-08 16:41 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +//            setupFileProgress(file)
It's an oversight but it's fixed 😅

2021-11-08 16:42 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> -                    filePreview.scaleType = ImageView.ScaleType.CENTER_CROP
Because it's managed by glide

2021-11-09 08:56 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +        .centerCrop().into(this)
```suggestion
        .centerCrop()
        .into(this)
```

2021-11-09 12:07 UTC, KevinBoulongne approved these changes

2021-11-09 14:06 UTC, JorisBodin approved these changes

2021-11-09 14:06 UTC, merged