Add FileManager actions in CloudStorage
Infomaniak/android-kDrive pull request #330
Opened 2021-11-08 13:43 UTC by KevinBoulongne

Closes #163

2021-11-10 17:23 UTC, JorisBodin requested changes

2021-11-10 17:23 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
> +            // flags = flags or DocumentsContract.Document.FLAG_DIR_SUPPORTS_CREATE
Why this commented code?

2021-11-11 07:13 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
> +fun Context?.hasInternet(): Boolean =
This function needs the ACCESS_NETWORK_STATE permission, and the Core module doesn't have it.

If it means adding a new unused permission, I don't think adding unused code to the Core module is a good idea.

So I'll just remove this function.

2021-11-11 07:13 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
> +            // flags = flags or DocumentsContract.Document.FLAG_DIR_SUPPORTS_CREATE
Just an oversight.

2021-11-11 16:31 UTC, JorisBodin requested changes
When you move from one drive to another it makes a copy and not a move

2021-11-12 15:10 UTC, merged

2021-11-12 15:10 UTC, JorisBodin approved these changes