New home
Infomaniak/android-kDrive pull request #365
Opened 2021-11-22 17:56 UTC by JorisBodin

- [x] Show activities
- [ ] Show offline files
- [x] Show pictures
- [x] Merge PicturesFragment
- [x] Save last tabs
- [ ] Fix bug when the app does not launch directly on the home

2021-11-23 13:39 UTC, sirambd requested changes

2021-11-23 13:39 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/utils/TabViewPagerUtils.kt
> +                val position = (tabsViewPager.adapter as ViewPagerAdapter).tabs.find { it.button == checkedId }!!.position
I think a LinkedHashMap to avoid multiple loops would be better

2021-11-23 13:39 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/utils/TabViewPagerUtils.kt
> +        val button: Int
Add `@IdRes` to property button to secure it, and rename `button` to `buttonResId` may be 🤷🏽

2021-11-24 08:50 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/utils/TabViewPagerUtils.kt
> +        val position: Int,
I don't understand why you need to store position, knowing that it is used only once, and that you can get it from the list

2021-11-24 09:10 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
> +                .replace(R.id.picturesFragmentView, picturesFragment, "TOTO")
TOTO I think it's an oversight  😂, `PicturesFragment.TAG` it'll be a good idea i think

2021-11-24 09:29 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
> +        if (super.getItemViewType(position) == VIEW_TYPE_LOADING) {
I would have removed the if else and just made a global when as below
```kotlin
when(super.getItemViewType(position)){
            VIEW_TYPE_LOADING -> {
                // TODO
            }
            DisplayType.TITLE.layout ->{
                //TODO
            }
            DisplayType.PICTURE.layout -> {
                //TODO
            }
        }
```

2021-11-24 10:36 UTC, sirambd approved these changes

2021-11-25 12:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
> +        picturesAdapter.numberItemLoader = 12
Magic number. Maybe extract it to the companion object ?

2021-11-25 13:16 UTC, merged