Categories
Infomaniak/android-kDrive pull request #390
Opened 2021-11-30 07:07 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne kevin.boulongne@infomaniak.com

2021-11-30 13:02 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
> +            if (name != null) put("name", name)
OMG JAVA !!!! 🙀

2021-11-30 13:33 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
> +    fun editCategory(driveId: Int, categoryId: Int) = "${DRIVE_API}$driveId/category/$categoryId"
`editCategory` and `deleteCategory` is the same url, you can merge it, and differentiate them in the repository

2021-11-30 13:40 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +        if (fileCategoriesIds != null && fileCategoriesIds.isEmpty()) return emptyList()
You like really java 😱, in kotlin `isNullOrEmptyExists`

2021-11-30 13:47 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +        } as? List<Category> ?: emptyList()
unnecessary casting, remove the `as? List<Category>`

2021-11-30 13:50 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +            val drive = realm.where(Drive::class.java)
I think `currentDrive` it's more meaningful

2021-11-30 13:56 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +    fun getCategories(fileCategoriesIds: Array<Int>? = null): List<Category> {
This method only return categories for the currentDrive, i think it'll be good to rename this, example `getCurrentDriveCategories` what do you think ?

2021-11-30 14:37 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +            ?.mapNotNull { id -> categories.find { it.id == id } } // Sort the categories
```suggestion
        val sortedList = fileCategoriesIds?.withIndex()?.associate { it.value to it.index }?.let { orderList ->
            categories.sortedBy { orderList[it.id] }
        }
```

2021-11-30 14:41 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +            ?.mapNotNull { id -> categories.find { it.id == id } } // Sort the categories
```suggestion
        val sortedList = fileCategoriesIds?.withIndex()?.associate { it.value to it.index }?.let { orderList ->
            categories.sortedBy { orderList[it.id] }
        }

        return fileCategoriesIds
            ?.let { sortedList }
```

2021-12-01 13:11 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +            categoryRights?.let { realm.copyFromRealm(it, 0) }
Why a val ? I think it's not important here because we understand, just the `let` it's suffisant

2021-12-13 17:18 UTC, JorisBodin requested changes

2021-12-13 17:18 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CreateOrEditCategoryBottomSheetDialog.kt
> +            previousCategoryId == NO_PREVIOUS_CATEGORY_ID && !previousCategoryName.isNullOrEmpty() -> true
previousCategoryName?.isNotEmpty() == true

2021-12-23 10:39 UTC, JorisBodin approved these changes

2021-12-23 10:45 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
> +        }
```suggestion
        val body = arrayMapOf("color" to color).apply {
            name?.let { put("name", it) }
        }
```

2021-12-23 15:48 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +                destinationId?.let {
No need for a variable, you can just do it like this

```suggestion
                }?.let {
```

2021-12-23 16:30 UTC, sirambd approved these changes

2021-12-23 16:42 UTC, merged