Fix remove from favorite fragment
Infomaniak/android-kDrive pull request #421
Opened 2022-01-06 10:02 UTC by sirambd

Fix PR #417

2022-01-06 15:07 UTC, JorisBodin requested changes

2022-01-06 15:07 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
> +                if (fileList.isEmpty()) onEmptyList?.invoke()
Plz add Bracket

2022-01-06 15:12 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
> +                    val fileList = fileAdapter.getFileObjectsList(mainViewModel.realm)
👍🏽

2022-01-06 15:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
> +                            withVisibilitySort = false,
For a quick sort, but it's not important

2022-01-06 15:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
> +                            withVisibilitySort = false,
Removed

2022-01-06 15:16 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
> +                if (fileList.isEmpty()) onEmptyList?.invoke()
- 🤔 why not, 
 - fixed

2022-01-06 15:50 UTC, JorisBodin approved these changes

2022-01-07 13:13 UTC, KevinBoulongne approved these changes

2022-01-07 13:17 UTC, merged