Fixed a bug in ShareLink for Office files
Infomaniak/android-kDrive pull request #437
Opened 2022-01-17 10:35 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #431

2022-01-18 11:15 UTC, JorisBodin approved these changes

2022-01-19 09:00 UTC, sirambd requested changes
Bug when config changes, from the permission select dialog, all new updates are no longer considered.
Try to switch night/light mode from permission selections.

2022-01-19 10:43 UTC, KevinBoulongne commented
> Bug when config changes, from the permission select dialog, all new updates are no longer considered. Try to switch night/light mode from permission selections.

This bug was already there. Will be fixed in another PR.
An issue has been created: #442

2022-01-19 12:51 UTC, sirambd approved these changes

2022-01-19 12:52 UTC, merged