Fixed navigation issue when creating a Dropbox or Common folder
Infomaniak/android-kDrive pull request #446
Opened 2022-01-20 10:43 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #439

2022-01-21 17:37 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
> +    }
No need, we already have `AccountUtils.currentDriveId`

2022-01-21 18:11 UTC, sirambd commented
I refactored [CreateCommonFolderFragment](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-eb9e102ab58e1ced602ae2f601fe5ea107852a274872d7f28ad656a176f1e127) cleanly so that we can understand it better, and I removed what was unnecessary.

2022-01-21 18:24 UTC, sirambd commented
> 



> I refactored [CreateCommonFolderFragment](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-eb9e102ab58e1ced602ae2f601fe5ea107852a274872d7f28ad656a176f1e127) cleanly so that we can understand it better, and I removed what was unnecessary.
> 
> commit: [76a96f8](https://github.com/Infomaniak/android-kDrive/commit/76a96f889e985c6ea8e55c3fef1bb2e01eae1b24)

Can you continue refactor with [CreateDropBoxFolderFragment.kt](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-6e5dc698bc40dca50876442861058f194585b454f313de05bdfe87ca62c01bda) ?

2022-01-21 18:24 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
>  class CreateDropBoxFolderFragment : CreateFolderFragment() {
Need refactor

2022-01-21 18:27 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
> +                        FileController.addFileTo(newFolderViewModel.currentFolderId.value!!, file)
It's better to have this in the `ViewModel`, it will allow you to avoid `Dispatchers` and `isResume`

2022-01-21 18:38 UTC, sirambd requested changes
Waiting feedback fix

2022-01-24 10:53 UTC, JorisBodin approved these changes

2022-01-24 13:44 UTC, sirambd approved these changes

2022-01-24 14:45 UTC, merged