Added the big 'open with' button when filetype can't be previewed
Infomaniak/android-kDrive pull request #463
Opened 2022-01-24 09:05 UTC by LunarX

2022-01-24 10:07 UTC, KevinBoulongne approved these changes

2022-01-25 08:58 UTC, sirambd commented on app/src/main/res/layout/fragment_preview_others.xml
> +        tools:text="Open with" />
Not need here, just `android:text` it's enough

2022-01-25 13:17 UTC, JorisBodin requested changes

2022-01-25 13:17 UTC, JorisBodin commented on app/src/main/res/layout/fragment_preview_others.xml
> +        android:id="@+id/openWithButton"
Hide this button when not needed

2022-01-25 16:36 UTC, JorisBodin approved these changes

2022-01-25 16:36 UTC, merged