Refactor Bulk Actions
Infomaniak/android-kDrive pull request #473
Opened 2022-01-25 13:38 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

2022-01-25 14:12 UTC, JorisBodin approved these changes

2022-01-27 10:38 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +        ) {
```suggestion
        val canBulkAllSelectedFiles = fileAdapter.allSelected && fileCount > BulkOperationsUtils.MIN_SELECTED
        if (canBulkAllSelectedFiles || selectedFiles.size > BulkOperationsUtils.MIN_SELECTED) {
```

2022-01-27 10:42 UTC, sirambd requested changes
Wait fix feedbacks

2022-01-27 13:44 UTC, sirambd approved these changes

2022-01-27 13:44 UTC, merged