Pictures backup custom date
Infomaniak/android-kDrive pull request #475
Opened 2022-01-25 14:32 UTC by LunarX

Closes #284

2022-01-25 15:10 UTC, KevinBoulongne requested changes

2022-01-25 15:10 UTC, KevinBoulongne commented on app/src/main/res/layout/view_date_input.xml
>          android:layout_height="wrap_content"
```suggestion
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/marginStandardMedium"
```

2022-01-27 13:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +//    private var customDate = Date().startOfTheDay()
```suggestion
```

2022-01-27 13:14 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +                syncDatePicker.isVisible = true
```suggestion
                syncDatePicker.apply {
                    text = it.format(FORMAT_DATE_CLEAR_MONTH)
                    isVisible = true
                }
```

2022-01-27 13:18 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +                SyncSettings.SavePicturesDate.SINCE_DATE -> syncSettingsViewModel.customDate.value ?: Date()
_Alt+Enter / "Add import for"_

2022-01-27 13:39 UTC, KevinBoulongne approved these changes

2022-01-27 14:21 UTC, JorisBodin requested changes

2022-01-27 14:21 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +                show(supportFragmentManager, "syncDate")
Wrong tag fragment

2022-01-27 14:21 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +            SelectSaveDateBottomSheetDialog().show(supportFragmentManager, "SyncSettingsSaveDateBottomSheetDialog")
Wrong tag fragment

2022-01-27 14:21 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
> +                }
```suggestion
                isGone = date == null
                text = date?.format(FORMAT_DATE_CLEAR_MONTH) ?: ""
```

2022-01-28 10:56 UTC, JorisBodin approved these changes

2022-01-28 10:56 UTC, merged