Fixed icons tint
Infomaniak/android-kDrive pull request #500
Opened 2022-02-02 09:30 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #499

2022-02-02 16:55 UTC, JorisBodin requested changes

2022-02-02 16:55 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
>      return if (isFolder()) {
The isFolder() is not necessary

2022-02-02 16:55 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
> +            val (icon, tint) = file.getFolderIcon()
We get the folderIcon even before checking if it is a folder

2022-02-03 08:53 UTC, JorisBodin approved these changes

2022-02-03 09:48 UTC, sirambd approved these changes

2022-02-03 09:48 UTC, merged