Fix illegal state exception for move file
Infomaniak/android-kDrive pull request #505
Opened 2022-02-02 16:30 UTC by sirambd

After several tests, I managed to reproduce it once but making my phone slow down, er in case the phone is in standby mode, but the file is still taken into account and well saved, so we can just ignore this exception

Close #503

2022-02-02 16:57 UTC, JorisBodin approved these changes

2022-02-03 08:19 UTC, KevinBoulongne requested changes

2022-02-03 08:19 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
> +                    runCatching { localFolder.children.add(file) }
I think we should add the issue link as a comment, above this line.

`https://github.com/Infomaniak/android-kDrive/issues/503`

2022-02-03 09:52 UTC, KevinBoulongne approved these changes

2022-02-03 11:33 UTC, JorisBodin approved these changes

2022-02-03 11:33 UTC, merged