Fix bulk selection for offline and favorite
Infomaniak/android-kDrive pull request #541
Opened 2022-02-10 10:03 UTC by FabianDevel

Fix the behaviours of setting/removing offline file and favorite in bulk.
From : only possibility of adding file to favorite/offline
To : When only already added files are selected, change the button to its remove version and remove all the selection

2022-02-10 10:32 UTC, KevinBoulongne requested changes
`strings.xml` files have been edited manually.
They should be updated via Loco.
We'll see that together on Monday.

2022-02-14 12:19 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ActionMultiSelectBottomSheetDialog.kt
> +        with(navigationArgs) {
You can lift it in the method declaration.

2022-02-14 12:26 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +        } else Utils.downloadAsOfflineFile(requireContext(), file)
```suggestion
        } else {
            Utils.downloadAsOfflineFile(requireContext(), file)
        }
```

2022-02-14 12:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
> +                    currentFile.currentProgress = 0
```suggestion
                currentFile.apply {
                    if (isNotManagedByRealm()) {
                        isOffline = true
                        currentProgress = 0
                    }
```

2022-02-15 07:43 UTC, KevinBoulongne approved these changes

2022-02-15 10:13 UTC, KevinBoulongne approved these changes

2022-02-15 16:49 UTC, JorisBodin approved these changes

2022-02-16 11:05 UTC, sirambd approved these changes

2022-02-16 13:17 UTC, merged