Factorize multi select layout
Infomaniak/android-kDrive pull request #602
Opened 2022-02-25 07:36 UTC by KevinBoulongne

2022-02-25 15:57 UTC, JorisBodin approved these changes

2022-02-28 10:33 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
> +    private fun setMultiSelectClickListeners(multiSelectLayout: MultiSelectLayoutBinding) = with(multiSelectLayout) {
```suggestion
    private fun MultiSelectLayoutBinding .setMultiSelectClickListeners() {
```

2022-02-28 10:35 UTC, sirambd requested changes
Wait request changes

2022-03-01 10:29 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
> +    private fun setMultiSelectClickListeners(multiSelectLayout: MultiSelectLayoutBinding) = with(multiSelectLayout) {
Done.

2022-03-01 10:37 UTC, sirambd approved these changes

2022-03-01 10:38 UTC, merged