Factorized bulk opérations
Infomaniak/android-kDrive pull request #607
Opened 2022-03-02 07:31 UTC by KevinBoulongne

Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes: #600

2022-03-08 16:22 UTC, JorisBodin requested changes

2022-03-08 16:22 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
> +        selectedFilesCount: Int? = null,
You have to explain to me what it is used for, knowing that after we call `getValidSelectedItems `
The only use I see is for the "all selected", so at that point rename it everywhere.

2022-03-09 10:01 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
> +        }
```suggestion
        if (fileSelectedNumber in 0..1) {
            val isEnabled = fileSelectedNumber == 1
            enableMultiSelectButtons(isEnabled)
        }
```

2022-03-09 10:10 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
> +                enableMultiSelectButtons(isEnabled)
```suggestion
                enableMultiSelectButtons(fileSelectedNumber == 1)
```

2022-03-09 12:36 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/FileListMultiSelectActionsBottomSheetDialog.kt
> +        }
You should avoid creating several instances of realm in a row like this

2022-03-09 13:45 UTC, JorisBodin approved these changes

2022-03-09 14:41 UTC, sirambd approved these changes

2022-03-09 14:59 UTC, merged