Transparent statusbar
Infomaniak/android-kDrive pull request #608
Opened 2022-03-02 13:04 UTC by LunarX

Closes #493

2022-03-03 12:44 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
> +        // If dark mode the icons stay white all along, no need to check
```suggestion
        // If in Light mode, change the status icons color to match the background.
        // If in Dark mode, the icons stay white all along, no need to check.
```

2022-03-03 12:45 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +
```suggestion
```

2022-03-04 09:31 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
> +        lastDestinationId = destination.id
Isn't there a better way ?

2022-03-04 13:43 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +                                ContextCompat.getColor(requireContext(), R.color.previewBackground), 128
Fix magic value

2022-03-04 13:44 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +                ContextCompat.getColor(requireContext(), R.color.previewBackground), 128
Same, magic value

2022-03-07 09:43 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +                    val peekHeight = getDefaultPeekHeight()
Use once, so no need for a variable

2022-03-07 09:48 UTC, sirambd requested changes
Wait changes

2022-03-07 09:55 UTC, sirambd approved these changes

2022-03-07 12:51 UTC, JorisBodin requested changes
Problem with CollapsingSubTitleToolbarBehavior in FileDetailsFragment

2022-03-07 13:22 UTC, JorisBodin approved these changes
https://github.com/Infomaniak/android-kDrive/issues/622

2022-03-07 13:22 UTC, merged