fix test crash at setup
Infomaniak/android-kDrive pull request #611
Opened 2022-03-03 10:28 UTC by FabianDevel

Fix the crashes by adding the user only if he's not in the db instead of if he's the current user
Set the user ApiToken even if the user is already logged because it can be an empty string

2022-03-03 11:26 UTC, KevinBoulongne approved these changes

2022-03-07 18:03 UTC, JorisBodin requested changes

2022-03-07 18:03 UTC, JorisBodin commented on app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
> +            if (newUser != null) removeUser(context, newUser)
Use a let plz

2022-03-08 10:27 UTC, KevinBoulongne approved these changes

2022-03-08 13:05 UTC, JorisBodin requested changes

2022-03-08 13:05 UTC, JorisBodin commented on app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
> +        if (currentUser == null) currentUser = user
Use `AccountUtils.currentUser` plz

2022-03-08 14:20 UTC, JorisBodin approved these changes

2022-03-08 16:25 UTC, JorisBodin approved these changes

2022-03-09 09:58 UTC, merged