Fix edge to edge mode
Infomaniak/android-kDrive pull request #652
Opened 2022-03-16 10:16 UTC by FabianDevel

closes #648 and #651

2022-03-16 12:43 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
> +        super.onStart()
Put it in the beginning of the method.

2022-03-16 12:43 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +        super.onStart()
Put it in the beginning of the method.

2022-03-16 17:40 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +                    bottomSheetFileInfos.setPadding(0, 0, 0, top + bottom)
Need comment here

2022-03-16 17:43 UTC, sirambd requested changes
Waiting for feedback resolution

2022-03-17 08:34 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
> +                    bottomSheetFileInfos.setPadding(0, 0, 0, top + bottom)
done :)

2022-03-17 09:29 UTC, merged