Fix unsupported characters
Infomaniak/android-kDrive pull request #704
Opened 2022-03-24 09:48 UTC by FabianDevel

closes #680 

Do not start offline downloading if file name contains characters forbidden by android/linux filesystem
Display a snack bar for the user

2022-03-24 11:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/drive/utils/Utils.kt
>              .enqueueUniqueWork(DownloadWorker.TAG, ExistingWorkPolicy.APPEND_OR_REPLACE, downloadRequest)
```suggestion
        workManager.enqueueUniqueWork(DownloadWorker.TAG, ExistingWorkPolicy.APPEND_OR_REPLACE, downloadRequest)
```

2022-03-24 11:07 UTC, KevinBoulongne commented on app/src/main/res/values-de/strings.xml
> +    </plurals>
```suggestion
```

2022-03-24 11:07 UTC, KevinBoulongne commented on app/src/main/res/values-de/strings.xml
> +    </plurals>
```suggestion
```

2022-03-24 11:07 UTC, KevinBoulongne commented on app/src/main/res/values-de/strings.xml
> +    <string name="emptyFolder">Leerer Ordner</string>
```suggestion
```

2022-03-24 11:07 UTC, KevinBoulongne commented on app/src/main/res/values-de/strings.xml
> +    <string name="content">Inhalt</string>
```suggestion
```

2022-03-24 11:22 UTC, KevinBoulongne requested changes
Update strings in all 5 files like I did in the comments for the german one.

2022-03-24 12:26 UTC, KevinBoulongne commented on app/src/main/res/layout/view_file_info_actions.xml
> +
```suggestion
```

2022-03-24 12:57 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
> +            }
done

2022-03-24 12:58 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/utils/Utils.kt
>              .enqueueUniqueWork(DownloadWorker.TAG, ExistingWorkPolicy.APPEND_OR_REPLACE, downloadRequest)
done

2022-03-24 13:06 UTC, FabianDevel commented on app/src/main/res/layout/view_file_info_actions.xml
> +
done

2022-03-24 13:06 UTC, FabianDevel commented on app/src/main/res/values-de/strings.xml
> +    </plurals>
done

2022-03-24 13:06 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/drive/utils/Utils.kt
>              .enqueueUniqueWork(DownloadWorker.TAG, ExistingWorkPolicy.APPEND_OR_REPLACE, downloadRequest)
done

2022-03-25 10:36 UTC, KevinBoulongne approved these changes

2022-03-28 09:29 UTC, JorisBodin requested changes
We need a clearer message and now we can't see the progression in the filelist

2022-03-30 15:25 UTC, JorisBodin approved these changes

2022-03-30 15:25 UTC, merged