File's Categories are now nullable
Infomaniak/android-kDrive pull request #764
Opened 2022-04-26 07:17 UTC by KevinBoulongne

[Sentry: https://sentry.infomaniak.com/organizations/infomaniak/issues/12305/?project=3](https://sentry.infomaniak.com/organizations/infomaniak/issues/12305/?project=3)

2022-05-10 16:49 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/data/models/File.kt
> +    var categories: @RawValue RealmList<FileCategory>? = RealmList(),
No need for migration?

2022-06-02 08:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/models/File.kt
> +    var categories: @RawValue RealmList<FileCategory>? = RealmList(),
Yes migration is needed here

2022-06-02 08:15 UTC, sirambd requested changes
waiting for request changes

2022-06-02 09:41 UTC, KevinBoulongne commented
Waiting for API v2 to test it again.

2022-09-06 16:44 UTC, closed without merging