Automatically selects the filename without the extension
Infomaniak/android-kDrive pull request #788
Opened 2022-05-24 08:39 UTC by LunarX

Instead of a cross, the filename (without the extension) is automatically selected when the text field is focused

Closes: #778 
Closes: #752

2022-06-03 08:29 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
>      }
You don't have to do it every time you focus, just once when you create.

2022-06-03 08:36 UTC, sirambd requested changes
Waiting for request changes

2022-06-08 15:18 UTC, JorisBodin requested changes

2022-06-08 15:18 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
> +        post { setSelection(0, endIndex) }
It is necessary to merge the logic with this method
https://github.com/Infomaniak/android-kDrive/blob/master/app/src/main/java/com/infomaniak/drive/data/models/File.kt#L201

2022-06-20 05:18 UTC, KevinBoulongne approved these changes

2022-06-21 10:00 UTC, merged