Don't auto upload trashed files
Infomaniak/android-kDrive pull request #797
Opened 2022-05-31 08:22 UTC by LunarX

Add condition of file not being trashed when querying media store to upload files

Closes: #795

2022-06-01 14:43 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
> +        Build.VERSION.SDK_INT > Build.VERSION_CODES.R -> "AND ${MediaStore.Images.Media.IS_PENDING} = 0 AND ${MediaStore.Images.Media.IS_TRASHED} = 0"
`>=` instead of `>`

2022-06-01 14:45 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
> +    }
use a single fun with `MediaStore.MediaColumns.IS_PENDING` and `MediaStore.MediaColumns.IS_TRASHED`

2022-06-02 08:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
> +    private fun getConditions(): String = when {
rename to `moreCustomConditions`

2022-06-02 08:20 UTC, sirambd requested changes
Waiting for request changes

2022-06-02 10:10 UTC, sirambd approved these changes

2022-06-02 11:43 UTC, JorisBodin approved these changes

2022-06-02 11:43 UTC, merged