Fix: file moved stays in favorites file list
Infomaniak/android-kDrive pull request #960
Opened 2022-12-21 16:08 UTC by FabianDevel

closes #784

2022-12-22 10:55 UTC, sirambd requested changes

2022-12-22 10:55 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
> +
You can keep it as before and just simplify it in case you don't want to delete it

2022-12-22 10:55 UTC, sirambd commented on app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
> +            FileActivityType.FILE_MOVE_OUT -> removeFileWhenEnteringFolder(false, realm, returnResponse, currentFolder)
The name is too big, and I think we can largely simplify it, here, for example a name like `handleRemoveAction` is more simple

2023-01-02 09:31 UTC, sirambd approved these changes

2023-01-04 09:48 UTC, JorisBodin approved these changes

2023-01-04 09:48 UTC, merged